-------------- Coded by: Ayan Das -----------
-------------- Coded on: 06-May-2021 ---------
-------------- Coded for: Neuroflow Data Challenge -------------


/* NEUROFLOW DATA CHALLENGE - PART 2 Q1*/
SELECT EXTRACT(MONTH FROM A.CREATED_AT)||EXTRACT(YEAR FROM A.CREATED_AT) AS COHORT_MONTH,
COUNT(CASE WHEN EXTRACT(MONTH FROM EXERCISE_COMPLETION_DATE)||EXTRACT(YEAR FROM A.CREATED_AT) = EXTRACT(MONTH FROM A.CREATED_AT)||EXTRACT(YEAR FROM A.CREATED_AT) THEN 1 ELSE NULL END)/COUNT(1) AS PERCENTAGE
FROM USERS A
LEFT JOIN EXERCISES B
ON A.USER_ID=B.USER_ID
AND EXTRACT(MONTH FROM A.CREATED_AT)||EXTRACT(YEAR FROM A.CREATED_AT)=EXTRACT(MONTH FROM EXERCISE_COMPLETION_DATE)||EXTRACT(YEAR FROM EXERCISE_COMPLETION_DATE)
GROUP BY EXTRACT(MONTH FROM A.CREATED_AT)||EXTRACT(YEAR FROM A.CREATED_AT);


/* NEUROFLOW DATA CHALLENGE - PART 2 Q2*/
SELECT NO_OF_EXERCISES_COMPLETED,
COUNT(1) AS NO_OF_USERS 
FROM 
(SELECT USER_ID,
COUNT(1) AS NO_OF_EXERCISES_COMPLETED 
FROM EXERCISES 
GROUP BY USER_ID)
GROUP BY NO_OF_EXERCISES_COMPLETED;

/* ALTERNATE QUERY FOR NEUROFLOW DATA CHALLENGE - PART 2 Q2*/
SELECT DISTINCT NO_OF_EXERCISES_COMPLETED,
COUNT(1) OVER (PARTITION BY NO_OF_EXERCISES_COMPLETED) AS NO_OF_USERS 
FROM 
(SELECT USER_ID,
COUNT(1) AS NO_OF_EXERCISES_COMPLETED 
FROM EXERCISES
GROUP BY USER_ID);

/* NEUROFLOW DATA CHALLENGE - PART 2 Q3 */
SELECT B.ORGANIZATION_NAME AS ORGANIZATION,
AVG(A.SCORE) AS AVG_SCORE 
FROM PHQ9 A 
INNER JOIN PROVIDERS B 
ON A.PROVIDER_ID=B.PROVIDER_ID 
GROUP BY B.ORGANIZATION_NAME 
ORDER BY AVG_SCORE DESC 
FETCH FIRST 5 ROWS ONLY;